window.COLLECTFOLIO_CONFIG = Object.freeze({
  SUPABASE_URL: 'https://agmjgyyvhfcivbwdlvzk.supabase.co',
  SUPABASE_ANON_KEY: '',
  APP_VERSION: '0.8.20-dev',
  TCGCSV_REFRESH_STATUS_URL: '',
  TCGCSV_CATALOG_URL: '',
  ENABLE_TESSERACT: true,
  ENABLE_WATCHLISTS: true,
  ENABLE_SET_BROWSING: true,
  ENABLE_PRICE_INTELLIGENCE: false,
  ENABLE_CLOUD_DATA_REMOVAL: false
});
