/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/tcgcsv-refresh/wrangler.jsonc --env=production --include-runtime=false cloudflare/tcgcsv-refresh/worker-configuration.d.ts` (hash: 61b89d1d3714898b96a9b58dbe6d9a78)
interface __BaseEnv_Env {
	TCGCSV_CURRENT: R2Bucket;
	SOURCE_UPDATED_URL: "https://tcgcsv.com/last-updated.txt";
	TCGCSV_USER_AGENT: "CollectFolio/0.8.5 private-current-refresh";
	ALLOWED_ORIGIN: "https://collectfolio-staging.netlify.app";
	LEASE_MINUTES: "90";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SOURCE_UPDATED_URL" | "TCGCSV_USER_AGENT" | "ALLOWED_ORIGIN" | "LEASE_MINUTES">> {}
}
