/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/tcgcsv-refresh/wrangler.jsonc --env=production --include-runtime=false cloudflare/tcgcsv-refresh/worker-configuration.d.ts` (hash: ca36a504d43b4c6cbb284bbb3375f672)
interface __BaseEnv_Env {
	TCGCSV_CURRENT: R2Bucket;
	SOURCE_UPDATED_URL: "https://tcgcsv.com/last-updated.txt";
	TCGCSV_USER_AGENT: "CollectFolio/0.8.6 private-current-refresh";
	ALLOWED_ORIGIN: "https://collectfolio-staging.netlify.app";
	LEASE_MINUTES: "90";
	CATALOG_LEASE_MINUTES: "180";
	CATALOG_AUTHENTICATED_TEST_ACCESS: "true";
	CATALOG_PUBLIC_ACCESS: "true";
	SUPABASE_URL: "https://agmjgyyvhfcivbwdlvzk.supabase.co";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SOURCE_UPDATED_URL" | "TCGCSV_USER_AGENT" | "ALLOWED_ORIGIN" | "LEASE_MINUTES" | "CATALOG_LEASE_MINUTES" | "CATALOG_AUTHENTICATED_TEST_ACCESS" | "CATALOG_PUBLIC_ACCESS" | "SUPABASE_URL">> {}
}
