"""Point-in-time, research-only analytics primitives for CollectFolio."""

from .baselines import BaselineForecast, damped_momentum, no_change
from .catalog_mapping import (
    ApprovedMapping,
    CanonicalCard,
    CatalogIngestionPacket,
    CanonicalSet,
    CanonicalVariant,
    ExternalProduct,
    MappingBatch,
    MappingCandidate,
    build_mapping_batch,
    build_catalog_ingestion_packet,
    map_external_product,
)
from .evaluation import (
    EvaluationSummary,
    ForecastCase,
    RealizedPrice,
    ResearchLineage,
    WalkForwardAudit,
    assert_features_known,
    evaluate_cases,
    realized_price_at_maturity,
    training_label_is_mature,
)
from .forecasting import (
    PromotionPolicy,
    ResearchForecastPacket,
    ResearchForecastPrediction,
    ResearchModelCard,
    ResearchScorecard,
    assess_research_scorecard,
    build_research_baseline_packet,
)
from .market_pipeline import (
    ObservationBatch,
    ObservationMapping,
    ObservationQualityPolicy,
    PreparedObservation,
    RawPriceRecord,
    SourceTerms,
    prepare_observation_batch,
    prepare_price_record,
)
from .justtcg import (
    JustTCGClient,
    JustTCGPayloadError,
    JustTCGSnapshot,
    JustTCGVariantSnapshot,
    assert_justtcg_production_terms,
    parse_justtcg_snapshot,
    prepare_justtcg_observation_batch,
)
from .monitoring import (
    OperationalAlert,
    PipelineHealthPolicy,
    PipelineHealthReport,
    assess_operator_packet,
)
from .observations import PriceObservation, PriceSeriesKey, point_in_time_series
from .publication import (
    DescriptiveCandidatePacket,
    PublicationLineage,
    aggregate_source_policy_hash,
    build_descriptive_candidate,
    build_trend_snapshot_row,
)
from .quantiles import QuantileOrderError, rearrange_quantiles, validate_quantiles
from .scarcity import PullMetrics, hit_probability, pull_metrics
from .trends import (
    TrendSnapshot,
    TrendThresholds,
    build_trend_snapshot,
    classify_trend,
    mad_log_return_volatility,
    max_drawdown,
    theil_sen_log_slope,
)
from .walk_forward import (
    HostedObservation,
    RetrospectiveWalkForwardConfig,
    RetrospectiveWalkForwardEvidence,
    build_retrospective_walk_forward,
    parse_hosted_observation_rows,
)
from .walk_forward_sql import build_walk_forward_evidence_sql
from .tcgcsv import (
    TCGCSVArchiveHistory,
    TCGCSVArchiveSnapshot,
    TCGCSVPayloadError,
    TCGCSVResearchClient,
    TCGCSVResearchPacket,
    TCGCSVSnapshot,
    assert_tcgcsv_research_terms,
    build_tcgcsv_research_packet,
)
from .qualification import (
    PrivateQualificationConfig,
    PrivateResearchEvidence,
    build_private_research_evidence,
    prepare_archive_observations,
)
from .private_sql import build_private_evidence_sql
from .video_model_v0 import VideoModelV0Audit, evaluate_video_model_v0

__all__ = [
    "BaselineForecast",
    "ApprovedMapping",
    "CanonicalCard",
    "CanonicalSet",
    "CanonicalVariant",
    "CatalogIngestionPacket",
    "DescriptiveCandidatePacket",
    "EvaluationSummary",
    "ForecastCase",
    "ExternalProduct",
    "MappingBatch",
    "MappingCandidate",
    "JustTCGClient",
    "JustTCGPayloadError",
    "JustTCGSnapshot",
    "JustTCGVariantSnapshot",
    "ObservationBatch",
    "ObservationMapping",
    "ObservationQualityPolicy",
    "OperationalAlert",
    "PipelineHealthPolicy",
    "PipelineHealthReport",
    "PreparedObservation",
    "PrivateQualificationConfig",
    "PrivateResearchEvidence",
    "PromotionPolicy",
    "PriceObservation",
    "PriceSeriesKey",
    "PublicationLineage",
    "PullMetrics",
    "QuantileOrderError",
    "RealizedPrice",
    "ResearchLineage",
    "ResearchForecastPacket",
    "ResearchForecastPrediction",
    "ResearchModelCard",
    "ResearchScorecard",
    "RawPriceRecord",
    "SourceTerms",
    "TrendSnapshot",
    "TrendThresholds",
    "TCGCSVArchiveHistory",
    "TCGCSVArchiveSnapshot",
    "TCGCSVPayloadError",
    "TCGCSVResearchClient",
    "TCGCSVResearchPacket",
    "TCGCSVSnapshot",
    "VideoModelV0Audit",
    "WalkForwardAudit",
    "assert_features_known",
    "assert_justtcg_production_terms",
    "assess_research_scorecard",
    "assess_operator_packet",
    "assert_tcgcsv_research_terms",
    "aggregate_source_policy_hash",
    "build_trend_snapshot",
    "build_catalog_ingestion_packet",
    "build_descriptive_candidate",
    "build_mapping_batch",
    "build_private_evidence_sql",
    "build_private_research_evidence",
    "build_research_baseline_packet",
    "build_trend_snapshot_row",
    "build_tcgcsv_research_packet",
    "classify_trend",
    "damped_momentum",
    "evaluate_cases",
    "evaluate_video_model_v0",
    "hit_probability",
    "mad_log_return_volatility",
    "map_external_product",
    "max_drawdown",
    "no_change",
    "point_in_time_series",
    "parse_justtcg_snapshot",
    "prepare_observation_batch",
    "prepare_archive_observations",
    "prepare_price_record",
    "prepare_justtcg_observation_batch",
    "pull_metrics",
    "rearrange_quantiles",
    "realized_price_at_maturity",
    "theil_sen_log_slope",
    "validate_quantiles",
    "training_label_is_mature",
    "HostedObservation",
    "RetrospectiveWalkForwardConfig",
    "RetrospectiveWalkForwardEvidence",
    "build_retrospective_walk_forward",
    "parse_hosted_observation_rows",
    "build_walk_forward_evidence_sql",
]
